In [ ]:
#Shahriyar Shahid

In [1]:
import pandas as pd
import numpy as np

In [2]:
columns =['sepal_length', 'sepal-width', 'petal_length', 'petal_width', 'species']
iris=pd.read_csv("iris.csv", header=None, names=columns) #iris.columns
iris.head()

   sepal_length  sepal-width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
iris.isna().sum()

sepal_length    0
sepal-width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [4]:
display(iris.dtypes)

sepal_length    float64
sepal-width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [5]:
iris['species'].value_counts()

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [6]:
iris.describe()

       sepal_length  sepal-width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [18]:
label_encoder=LabelEncoder()
X=iris.drop('species', axis=1)
y=iris['species']

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
dt_classifier=DecisionTreeClassifier(random_state=42)

In [21]:
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [22]:
y_pred=dt_classifier.predict(X_test)
y_pred

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa'], dtype=object)

In [23]:
accuracy=accuracy_score(y_test, y_pred)
accuracy

1.0

In [24]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
label_encoder=LabelEncoder()
train['Class']=label_encoder.fit_transform(train['Class'])
train

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
0,54180,951.753,388.728347,178.948203,2.172295,0.887741,55014,262.648279,0.580210,0.984840,0.751624,0.675660,0.007175,0.000922,0.456517,0.991689,4
1,42023,746.715,272.962686,196.334047,1.390297,0.694730,42365,231.312225,0.795348,0.991927,0.947081,0.847413,0.006496,0.002066,0.718109,0.998386,3
2,38600,716.517,254.129288,193.991641,1.310001,0.645976,38940,221.691331,0.715265,0.991269,0.944809,0.872356,0.006584,0.002352,0.761006,0.996919,5
3,62298,992.583,327.685094,242.658033,1.350399,0.672032,63353,281.638558,0.801157,0.983347,0.794603,0.859479,0.005260,0.001771,0.738705,0.997546,0
4,74456,1085.466,447.665972,212.382328,2.107831,0.880298,75096,307.896612,0.788821,0.991478,0.794104,0.687782,0.006012,0.000830,0.473044,0.997097,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9523,55381,914.969,363.142352,194.498350,1.867072,0.844473,55974,265.543366,0.765216,0.989406,0.831300,0.731238,0.006557,0.001156,0.534709,0.998339,4
9524,40987,749.125,272.565043,192.210719,1.418053,0.709016,41441,228.443142,0.708701,0.989045,0.917799,0.838123,0.006650,0.002024,0.702451,0.996113,6
9525,32168,663.090,239.983107,171.160719,1.402092,0.700940,32570,202.379766,0.727536,0.987657,0.919367,0.843308,0.007460,0.002327,0.711169,0.997125,3
9526,53228,920.083,380.325304,178.969940,2.125079,0.882362,53905,260.330549,0.653939,0.987441,0.790125,0.684494,0.007145,0.000968,0.468533,0.995669,4
9527,50330,841.897,324.437513,198.042350,1.638223,0.792080,50882,253.144517,0.734316,0.989151,0.892316,0.780257,0.006446,0.001474,0.608800,0.997351,6

In [25]:
test=pd.read_csv('Test.csv')
train=pd.read_csv('Train.csv')
test, train

(       Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
 0     29380    624.110       212.826130       175.931143      1.209713
 1     30008    645.884       210.557999       182.516516      1.153638
 2     30279    634.927       212.560556       181.510182      1.171067
 3     31107    640.594       214.648549       184.969253      1.160455
 4     31203    639.782       215.067737       184.874876      1.163315
 ...     ...        ...              ...              ...           ...
 4078  41979    757.238       272.579920       196.580706      1.386606
 4079  42008    759.454       280.332717       191.218136      1.466036
 4080  42012    778.043       297.912812       179.711836      1.657725
 4081  42070    760.701       276.691651       193.945366      1.426647
 4082  42101    757.499       281.576392       190.713136      1.476439

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
 0         0.562727       29690     193.410904  0.778113  0.989559   0.947849
 1         0.498616       30724     195.467062  0.782681  0.976696   0.903936
 2         0.520401       30600     196.347702  0.775688  0.989510   0.943852
 3         0.507366       31423     199.014227  0.761046  0.989944   0.952582
 4         0.510947       31558     199.321081  0.762984  0.988751   0.957949
 ...            ...         ...            ...       ...       ...        ...
 4078      0.692742       42362     231.191096  0.722381  0.990959   0.919977
 4079      0.731248       42419     231.270938  0.711710  0.990311   0.915248
 4080      0.797562       42544     231.281949  0.715805  0.987495   0.872120
 4081      0.713216       42458     231.441543  0.730813  0.990862   0.913596
 4082      0.735702       42494     231.526798  0.799943  0.990752   0.922015

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
 0        0.908774      0.007244      0.003048      0.825871      0.999066
 1        0.928329      0.007017      0.003215      0.861794      0.994199
 2        0.923726      0.007020      0.003153      0.853270      0.999236
 3        0.927163      0.006900      0.003145      0.859632      0.997564
 4        0.926783      0.006893      0.003137      0.858926      0.999202
 ...           ...           ...           ...           ...           ...
 4078     0.848159      0.006493      0.002073      0.719374      0.997487
 4079     0.824987      0.006673      0.001907      0.680604      0.997790
 4080     0.776341      0.007091      0.001589      0.602705      0.999120
 4081     0.836460      0.006577      0.001986      0.699666      0.998176
 4082     0.822252      0.006688      0.001886      0.676099      0.998219

          Class
 0        SEKER
 1        SEKER
 2        SEKER
 3        SEKER
 4        SEKER
 ...        ...
 4078  DERMASON
 4079  DERMASON
 4080  DERMASON
 4081  DERMASON
 4082  DERMASON

 [4083 rows x 17 columns],
        Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \
 0     54180    951.753       388.728347       178.948203      2.172295
 1     42023    746.715       272.962686       196.334047      1.390297
 2     38600    716.517       254.129288       193.991641      1.310001
 3     62298    992.583       327.685094       242.658033      1.350399
 4     74456   1085.466       447.665972       212.382328      2.107831
 ...     ...        ...              ...              ...           ...
 9523  55381    914.969       363.142352       194.498350      1.867072
 9524  40987    749.125       272.565043       192.210719      1.418053
 9525  32168    663.090       239.983107       171.160719      1.402092
 9526  53228    920.083       380.325304       178.969940      2.125079
 9527  50330    841.897       324.437513       198.042350      1.638223

       Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \
 0         0.887741       55014     262.648279  0.580210  0.984840   0.751624
 1         0.694730       42365     231.312225  0.795348  0.991927   0.947081
 2         0.645976       38940     221.691331  0.715265  0.991269   0.944809
 3         0.672032       63353     281.638558  0.801157  0.983347   0.794603
 4         0.880298       75096     307.896612  0.788821  0.991478   0.794104
 ...            ...         ...            ...       ...       ...        ...
 9523      0.844473       55974     265.543366  0.765216  0.989406   0.831300
 9524      0.709016       41441     228.443142  0.708701  0.989045   0.917799
 9525      0.700940       32570     202.379766  0.727536  0.987657   0.919367
 9526      0.882362       53905     260.330549  0.653939  0.987441   0.790125
 9527      0.792080       50882     253.144517  0.734316  0.989151   0.892316

       Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \
 0        0.675660      0.007175      0.000922      0.456517      0.991689
 1        0.847413      0.006496      0.002066      0.718109      0.998386
 2        0.872356      0.006584      0.002352      0.761006      0.996919
 3        0.859479      0.005260      0.001771      0.738705      0.997546
 4        0.687782      0.006012      0.000830      0.473044      0.997097
 ...           ...           ...           ...           ...           ...
 9523     0.731238      0.006557      0.001156      0.534709      0.998339
 9524     0.838123      0.006650      0.002024      0.702451      0.996113
 9525     0.843308      0.007460      0.002327      0.711169      0.997125
 9526     0.684494      0.007145      0.000968      0.468533      0.995669
 9527     0.780257      0.006446      0.001474      0.608800      0.997351

          Class
 0        HOROZ
 1     DERMASON
 2        SEKER
 3     BARBUNYA
 4        HOROZ
 ...        ...
 9523     HOROZ
 9524      SIRA
 9525  DERMASON
 9526     HOROZ
 9527      SIRA

 [9528 rows x 17 columns])

In [26]:
display(test.shape, train.shape)

(4083, 17)

(9528, 17)

In [27]:
display(test.describe(), train.describe())

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4
count,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000,4083.000000
mean,52564.673524,852.033817,319.137432,201.298586,1.585725,0.752378,53283.909870,252.055118,0.748994,0.987016,0.872868,0.799041,0.006592,0.001716,0.642191,0.994937
std,28645.358590,211.126243,84.442374,44.334712,0.244526,0.090468,29077.775196,58.279243,0.048860,0.004796,0.059175,0.061036,0.001125,0.000593,0.097803,0.004605
min,20420.000000,524.932000,183.601165,132.187521,1.024868,0.218951,20684.000000,161.243764,0.572209,0.946634,0.489618,0.651631,0.002856,0.000567,0.424623,0.955032
25%,36087.000000,701.621500,252.660111,174.761997,1.433740,0.716607,36469.000000,214.353436,0.716429,0.985578,0.830937,0.761909,0.005907,0.001152,0.580506,0.993614
50%,44453.000000,791.480000,296.398632,191.664022,1.553746,0.765357,44946.000000,237.906111,0.758447,0.988213,0.883335,0.800519,0.006675,0.001691,0.640830,0.996358
75%,61035.000000,974.456000,375.418250,216.783314,1.708823,0.810890,61916.000000,278.769035,0.786370,0.989910,0.916033,0.833791,0.007316,0.002167,0.695207,0.997814
max,237270.000000,1921.685000,738.144502,449.339678,2.347666,0.904744,240671.000000,549.637650,0.858420,0.994677,0.987920,0.987303,0.009653,0.003506,0.974767,0.999612

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4
count,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000,9528.000000
mean,53255.524664,856.676016,320.572294,202.687297,1.582178,0.750259,53975.731423,253.496647,0.750049,0.987197,0.873459,0.800216,0.006551,0.001716,0.644190,0.995117
std,29609.257209,215.627112,86.225872,45.235551,0.247600,0.092649,30067.830953,59.555540,0.049182,0.004600,0.059669,0.062001,0.001129,0.000597,0.099502,0.004259
min,20464.000000,524.736000,183.965251,122.512653,1.036423,0.262774,20772.000000,161.417391,0.555315,0.919246,0.556766,0.640577,0.002778,0.000564,0.410339,0.947687
25%,36453.750000,704.791500,253.499188,176.261896,1.430546,0.715089,36844.750000,215.439913,0.719528,0.985704,0.832908,0.762764,0.005899,0.001154,0.581809,0.993739
50%,44754.500000,796.506000,297.211791,192.789907,1.549658,0.763926,45290.500000,238.711540,0.760305,0.988315,0.883106,0.801603,0.006632,0.001695,0.642568,0.996396
75%,61444.750000,977.826000,376.865074,217.042845,1.706178,0.810235,62391.000000,279.703209,0.787088,0.990065,0.917196,0.834551,0.007256,0.002172,0.696476,0.997909
max,254616.000000,1985.370000,738.860153,460.198497,2.430306,0.911423,263261.000000,569.374358,0.866195,0.994213,0.990685,0.981611,0.010451,0.003665,0.963560,0.999733

In [28]:
train.isna().sum(), test.isna().sum()

(Area               0
 Perimeter          0
 MajorAxisLength    0
 MinorAxisLength    0
 AspectRation       0
 Eccentricity       0
 ConvexArea         0
 EquivDiameter      0
 Extent             0
 Solidity           0
 roundness          0
 Compactness        0
 ShapeFactor1       0
 ShapeFactor2       0
 ShapeFactor3       0
 ShapeFactor4       0
 Class              0
 dtype: int64,
 Area               0
 Perimeter          0
 MajorAxisLength    0
 MinorAxisLength    0
 AspectRation       0
 Eccentricity       0
 ConvexArea         0
 EquivDiameter      0
 Extent             0
 Solidity           0
 roundness          0
 Compactness        0
 ShapeFactor1       0
 ShapeFactor2       0
 ShapeFactor3       0
 ShapeFactor4       0
 Class              0
 dtype: int64)

In [29]:
train['Class'].value_counts(), test['Class'].value_counts()

(Class
 DERMASON    2427
 SIRA        1850
 SEKER       1468
 HOROZ       1341
 CALI        1137
 BARBUNYA     928
 BOMBAY       377
 Name: count, dtype: int64,
 Class
 DERMASON    1119
 SIRA         786
 HOROZ        587
 SEKER        559
 CALI         493
 BARBUNYA     394
 BOMBAY       145
 Name: count, dtype: int64)

In [33]:
X=train.drop('Class', axis=1)
y=train['Class']

In [34]:
dt_classifier=DecisionTreeClassifier()
dt_classifier.fit(X,y)

DecisionTreeClassifier()

In [35]:
pred=dt_classifier.predict(X)
train_pred

array(['HOROZ', 'DERMASON', 'SEKER', ..., 'DERMASON', 'HOROZ', 'SIRA'],
      dtype=object)

In [36]:
accuracy=accuracy_score(y,pred)
accuracy

1.0

In [37]:
X_test=test.drop('Class', axis=1)
y_test=test['Class']

In [38]:
testpred=dt_classifier.predict(X_test)
pred

array(['HOROZ', 'DERMASON', 'SEKER', ..., 'DERMASON', 'HOROZ', 'SIRA'],
      dtype=object)

In [39]:
accuracy=accuracy_score(y_test, testpred)
accuracy

0.8853783982365907