In [ ]:
#Shahriyar Shahid

In [2]:
import pandas as pd

In [3]:
df1=pd.DataFrame({"key":[1,2,3,4], "value":['A','B','C','D']})
df2=pd.DataFrame({"key":[1,2,3,4], "value":['E','F','G','H']})
display(df1,df2)

   key value
0    1     A
1    2     B
2    3     C
3    4     D

   key value
0    1     E
1    2     F
2    3     G
3    4     H

In [4]:
df1.columns=('value', 'key')
display(df1)

   value key
0      1   A
1      2   B
2      3   C
3      4   D

In [6]:
df1.drop('value', axis=1, inplace=True)
display(df1)

  key
0   A
1   B
2   C
3   D

In [7]:
df1.drop(1, axis=0, inplace=True)
display(df1)

  key
0   A
2   C
3   D

In [52]:
concat=pd.concat([df1,df2], ignore_index=True)
concat

   key value
0    1     A
1    2     B
2    3     C
3    4     D
4    1     E
5    2     F
6    3     G
7    4     H

In [3]:
import pandas as pd
wine=pd.read_csv("winequality-white.csv", sep=";")
wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [4]:
wine['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

In [5]:
wine['alcohol'].mean()

10.514267047774602

In [6]:
wine.loc[(wine['pH']<7)] #acidic
wine.loc[(wine['pH']==7)] #neutral
wine.loc[(wine['pH']>7)] #bacis

Empty DataFrame
Columns: [fixed acidity, volatile acidity, citric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, quality]
Index: []

In [106]:
wine['quality'].mean()

5.87790935075541

In [114]:
wine['quality'].sort_values(ascending=False) #descending order

827     9
1605    9
876     9
774     9
820     9
       ..
1484    3
2373    3
251     3
1688    3
253     3
Name: quality, Length: 4898, dtype: int64

In [118]:
wine['quality'].sort_values(ascending=True) #ascending order
wine['quality'].sort_values()

3307    3
445     3
2050    3
3810    3
3409    3
       ..
774     9
827     9
876     9
820     9
1605    9
Name: quality, Length: 4898, dtype: int64

In [4]:
white=pd.read_csv("winequality-white.csv", sep=";")
red=pd.read_csv("winequality-red.csv", sep=";")
display(white,red)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [3]:
concate=pd.concat([white,red], ignore_index=True)
concate

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
6494,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [14]:
concate=red+white
display(concate.head(10))

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,14.4,0.97,0.36,22.6,0.121,56.0,204.0,1.9988,6.51,1.01,18.2,11.0
1,14.1,1.18,0.34,4.2,0.147,39.0,199.0,1.9908,6.50,1.17,19.3,11.0
2,15.9,1.04,0.44,9.2,0.142,45.0,151.0,1.9921,6.52,1.09,19.9,11.0
3,18.4,0.51,0.88,10.4,0.133,64.0,246.0,1.9936,6.35,0.98,19.7,12.0
4,14.6,0.93,0.32,10.4,0.134,58.0,220.0,1.9934,6.70,0.96,19.3,11.0
5,15.5,0.94,0.40,8.7,0.125,43.0,137.0,1.9929,6.77,1.00,19.5,11.0
6,14.1,0.92,0.22,8.6,0.114,45.0,195.0,1.9913,6.48,0.93,19.0,11.0
7,14.3,0.92,0.36,21.9,0.110,60.0,191.0,1.9956,6.39,0.92,18.8,13.0
8,14.1,0.88,0.36,3.6,0.122,23.0,150.0,1.9908,6.66,1.06,19.0,13.0
9,15.6,0.72,0.79,7.6,0.115,45.0,231.0,1.9916,6.57,1.25,21.5,11.0