In [26]:
import pandas as pd
import numpy as np
#sepal length, sepal width, petal length, petal width, specie

In [27]:
columns =['sepal_length', 'sepal-width', 'petal_length', 'petal_width', 'species']
iris=pd.read_csv("iris.csv", header=None, names=columns) #iris.columns

In [28]:
iris.head(5)

   sepal_length  sepal-width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [29]:
iris.isna().sum()

sepal_length    0
sepal-width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [30]:
#display(iris.dtypes)
display(iris.dtypes)
iris.shape

sepal_length    float64
sepal-width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

(150, 5)

In [31]:
display(iris["species"].value_counts())

species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [32]:
iris.value_counts()

sepal_length  sepal-width  petal_length  petal_width  species
4.9           3.1          1.5           0.1          Iris-setosa        3
5.8           2.7          5.1           1.9          Iris-virginica     2
              4.0          1.2           0.2          Iris-setosa        1
5.9           3.0          4.2           1.5          Iris-versicolor    1
6.2           3.4          5.4           2.3          Iris-virginica     1
                                                                        ..
5.5           2.3          4.0           1.3          Iris-versicolor    1
              2.4          3.7           1.0          Iris-versicolor    1
                           3.8           1.1          Iris-versicolor    1
              2.5          4.0           1.3          Iris-versicolor    1
7.9           3.8          6.4           2.0          Iris-virginica     1
Name: count, Length: 147, dtype: int64

In [33]:
iris.describe()

       sepal_length  sepal-width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [34]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor

In [35]:
label_encoder= LabelEncoder()
iris['species']= label_encoder.fit_transform(iris['species'])
iris.head()

   sepal_length  sepal-width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [36]:
#separating independant and depandent
X=iris.drop('species', axis=1) 
y=iris['species']

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
#initialize the decisionn tree
dt_classifier=DecisionTreeClassifier(random_state=42)

In [39]:
#fit the model to the training data
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [40]:
X_test.shape

(30, 4)

In [41]:
y_pred= dt_classifier.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [42]:
y_pred
for i in y_pred:
    if i==0:
        print("versicolor")
    elif i==1:
        print("virginica")
    elif i==2:
        print("setosa")

virginica
versicolor
setosa
virginica
virginica
versicolor
virginica
setosa
virginica
virginica
setosa
versicolor
versicolor
versicolor
versicolor
virginica
setosa
virginica
virginica
setosa
versicolor
setosa
versicolor
setosa
setosa
setosa
setosa
setosa
versicolor
versicolor

In [43]:
#grid search CV

In [44]:
import matplotlib.pyplot as plt
%matplotlib inline

In [66]:
data=pd.read_csv('data_cleaned.csv')
data

,Survived,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
0,0,22.000000,7.2500,0,0,1,0,1,0,1,...,1,0,0,0,0,0,0,0,0,1
1,1,38.000000,71.2833,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,1,0,0
2,1,26.000000,7.9250,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,0,0,1
3,1,35.000000,53.1000,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,1
4,0,35.000000,8.0500,0,0,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.000000,13.0000,0,1,0,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1
887,1,19.000000,30.0000,1,0,0,1,0,1,0,...,1,0,0,0,0,0,0,0,0,1
888,0,29.699118,23.4500,0,0,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,1
889,1,26.000000,30.0000,1,0,0,0,1,1,0,...,1,0,0,0,0,0,0,1,0,0
890,0,32.000000,7.7500,0,0,1,0,1,1,0,...,1,0,0,0,0,0,0,0,1,0

In [46]:
data.shape

(891, 25)

In [69]:
#separating
y_cleaned = data['Survived']
X_cleaned = data.drop(['Survived'], axis=1)

In [70]:
#creating the train and validation set
X_train_cleaned, X_val_cleaned, y_train_cleaned, y_val_cleaned = train_test_split(X_cleaned, y_cleaned, random_state=101, stratify=y_cleaned, test_size=0.25)

In [71]:
#import decision tree classifier
from sklearn.tree import DecisionTreeClassifier

In [64]:
#import decision tree function
dt_model=DecisionTreeClassifier(random_state=10)

In [73]:
#fitting the model
dt_model.fit(X_train_cleaned, y_train_cleaned)

DecisionTreeClassifier(random_state=10)

In [74]:
DecisionTreeClassifier(random_state=10)

DecisionTreeClassifier(random_state=10)